### ISSUE TITLE
/metrics/find API is not implemented on disthene-reader

### ISSUE THREAD

**Issue by ekdxhrl0096** [Dark0096/disthene-reader#1]
Grafana allows Grahpite datasource to import and use metric paths via the `metrics/find` api. There is no support for this and it is inconvenient to use.

**Comment by Dark0096** [comment]
Your request will resolve at below link.
https://github.com/Dark0096/disthene-reader/pull/2

**Comment by Dark0096** [comment]
Your request will resolve at below link.
#2
