### ISSUE TITLE
/render api not supported about asterisk query

### ISSUE THREAD

**Issue by ekdxhrl0096** [Dark0096/disthene-reader#3]
For example)
![image](https://user-images.githubusercontent.com/51398199/61183525-57763c00-a67d-11e9-8e5b-16ea0bd0bd48.png)

Why this api is not supported that?

**Comment by Dark0096** [comment]
Thanks for your report.

This issue will resolve due to https://github.com/Dark0096/disthene-reader/pull/4. So I close this issue.

Thanks.
