### ISSUE TITLE
Expose duplicated path on /render

### ISSUE THREAD

**Issue by ekdxhrl0096** [Dark0096/disthene-reader#5]
Below is the prove about duplicated metric key.

![image](https://user-images.githubusercontent.com/51398199/61439232-1bdcba00-a97c-11e9-8494-ccd5c5f8be92.png)

**Comment by Dark0096** [comment]
Thanks for your comment.

This bug had resolved at below link.
https://github.com/Dark0096/disthene-reader/pull/9
